puts "Right arm out in front of you, palm facing down."
puts "Left arm out in front of you, palm facing down."
puts "Step 1 Turn your right palm up."
puts "Step 2 Turn your left palm up."
puts "Step 3 Place your right hand on your left shoulder."
puts "Step 4 Place your left hand on your right shoulder."
puts "Step 5 Bring your right hand up and around to the back of your head."
puts "Step 6 Bring your left hand up and around to the back your head."